[build]
  command = "npx prisma generate && npx prisma db push --skip-generate && npx prisma db seed && npm run build"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["src/generated/prisma/**", "prisma/dev.db"]
